[package]
name = "macros"
version = "0.1.0"
authors = ["captain <captain@captain>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]

